### PR TITLE
Try another implementation of memory leak

### PR DESCRIPTION
**Pull request by ptqa**

### CODE REVIEW

**Comment by stszap** [comment]
I tested this branch and it works just fine for me (memory usage returns to the same level even with a lot of "receive buffer errors"). I also like that clean up process is more predictable now. The only thing that concerns me a little is that messages are dropped silently. I used simple print command in my tests, but proper warning message with a number of dropped messages (if there are any) after each clean up would be nice. Not sure how to implement this since some users may want to suppers such messages.

**Comment by ptqa** [comment]
Well, it's UDP. People should sorta be aware it can loose packets. Also there is no logging system in this gem and I don't feel like implementing it (not even sure if it needs one). But PR's are welcome.

Ok, I merge just and publish gem. Keep in mind you have to update gemspec files in other gems that depend on this gem.

@stszap thanks for contribution!

**Comment by stszap** [comment]
Ok, I understand. Thank you too for quick release.

**Comment by stszap** [comment]
Maybe I'm doing something wrong but it seems that chunked_parser.rb from the gem is a little different from github version. For example cleanup_chunks() is never called there. Could you please check that?
This is chunked_parser.rb I get after `gem install gelfd2` : 
```
module Gelfd2
  class ChunkedParser
    class << self

      attr_accessor :message_id, :max_chunks, :decoded_data, :chunks, :seen

      def parse(data)
        @chunk_map ||= Hash.new { |hash, key| hash[key] = { total_chunks: 0, msg_ttl: 0, chunks: {} } }
        @msg_timeout ||= 20
        @last_cleanup ||= 0
        msg_id = parse_chunk(data)
        return unless @chunk_map[msg_id][:chunks].size == @chunk_map[msg_id][:total_chunks]
        assemble_chunks(msg_id)
      end

      def assemble_chunks(msg_id)
        buff = ''
        chunks = @chunk_map[msg_id][:chunks]
        chunks.keys.sort.each do |k|
          buff += chunks[k]
        end
        begin
          # TODO
          # This has a chance for an DoS
          # you can send a chunked message as a chunked message
          t = Parser.parse(buff.clone)
          @chunk_map.delete(msg_id)
          t
        rescue Exception => e
          "Exception: #{e.message}"
        end
      end

      def parse_chunk(data)
        header = data[0..1]
        raise NotChunkedDataError, "This doesn't look like a Chunked GELF message!" if header != CHUNKED_MAGIC
        begin
          msg_id = data[2..9].unpack('C*').join
          seq_number, total_number = data[10].ord, data[11].ord
          zlib_chunk = data[12..-1]
          raise TooManyChunksError, "#{total_number} greater than #{MAX_CHUNKS}" if total_number > MAX_CHUNKS
          @chunk_map[msg_id][:total_chunks] = total_number.to_i
          @chunk_map[msg_id][:chunks][seq_number.to_i] = zlib_chunk
          @chunk_map[msg_id][:ttl] = Time.now.to_i + @msg_timeout
          msg_id
        end
      end

      def cleanup_chunk
        # Run check every @msg_timeout seconds
        now = Time.now.to_i
        return unless now + @msg_timeout > @last_cleanup
        @last_cleanup = now
        begin
          @chunk_map.each do |msg_id, msg|
            next if msg[:ttl] > now
            @chunk_map.delete(msg_id)
          end
        end
      end
    end
  end
end
```

**Comment by ptqa** [comment]
@stszap yeah, probably I've uploaded old test build. Can you try now?

**Comment by stszap** [comment]
Version 0.4.1 works perfectly, thanks.

**Pull request merged**
